### PR TITLE
compatible swift3

### PR DESCRIPTION
**Pull request by phpmaple**

### CODE REVIEW

**Comment by DivineDominion** [comment]
🎉 Can you add Travis CI changes? 
https://github.com/naoty/SwiftCSV/pull/44/commits/27a5311e4a18f2ac4e7315bd8a086816e21e9279

**Comment by phpmaple** [comment]
travis ci also error?

**Comment by grantkemp** [comment]
This should be ok to merge and use - I have added it to my fork.

**Comment by grantkemp** [comment]
After testing - it seems to run nicely.  I picked up an error with how it parses the Rows which I want to fix - but this might be a good thing to include in the next point release @naoty

**Comment by DivineDominion** [comment]
Cool! What kind of error? (And did you fix it?)

**Comment by naoty** [comment]
Thank you for great jobs! I agree with @grantkemp.

@grantkemp Will you fix an error you found at this PR? Otherwise, I will merge this.

**Comment by grantkemp** [comment]
@naoty  I think merge it into Develop - and will apply my fix under this  issue: https://github.com/naoty/SwiftCSV/issues/51 
- its not directly related. 

I think the code needs a little bit of refactoring but it should be good to go onto swift 3

**Comment by grantkemp** [comment]
Have created develop branch for next point release.

**Comment by naoty** [comment]
I see. Thank you for your effort!

**Comment by grantkemp** [comment]
@phpmaple can you branch off and resubmit against our develop branch so you get the credit for your excellent work.  We are testing the release now.  and hope to release next week.

**Comment by DivineDominion** [comment]
Merged parts of this in #68 and #69 today. If I missed something, please notify me :)

**Pull request closed without merging**
