### PR TITLE
Release 0.5.6

### PR DESCRIPTION
**Pull request by lukestringer90**
This PR bumps the version number to 0.5.6. It contains the changes for adding quotes to the `description` property from #86. I assume bumping the patch number is fine for this sort of change?

Having read the [contributing guidelines](https://github.com/swiftcsv/SwiftCSV/blob/master/CONTRIBUTING.md#publishing-new-releases) I'm not sure I have permission to add tags to master and release a new version of the cocoapod. Is there anything more I need to do in this PR?

### CODE REVIEW

**Comment by lukestringer90** [comment]
@DivineDominion Anything else I should do here? I don't think I am part of the SwiftCSV GitHub Organization, so maybe I don't have the privileges make a release 🤔

**Comment by DivineDominion** [comment]
Sorry, I thought I had a bot set up successfully to do that, but I didn't :D The invitation went out now. Please try again

**Comment by lukestringer90** [comment]
Thanks, I've just accepted the invite.

**Comment by lukestringer90** [comment]
Thanks @DivineDominion, I've accepted the invite. It looks like I need write permission to approve this merge request. What is the best way forward from here? Should we discuss it over in the SwiftCSV releases team?

**Comment by DivineDominion** [comment]
@lukestringer90 I've modified the access rights; can you try to merge again? The org teams are unused at the moment, but I'll be happy to invite you to the de facto dead "releases" team if the default settings do not work :)

**Comment by lukestringer90** [comment]
Thanks @DivineDominion - I can merge this PR now. I'll try it out later when I've got more time. We can see if these access rights suffice for making a release before we do anything with the org.

**Comment by DivineDominion** [comment]
Why not both! I pushed the pod and added you to the CocoaPods owners team. Thanks for taking care of this release.

**Comment by lukestringer90** [comment]
Thanks @DivineDominion My pleasure to working on this release. I've found this project really useful in one of my apps so its great to give back.

**Pull request merged**
