### PR TITLE
Swift Package Manager

### PR DESCRIPTION
**Pull request by kgn**
I added support for Swift Package Manager, the changes needed to get this working were:
- Move source files into `Sources` directory
- Move test files into `Tests/SwiftCSVTests`
- Change how the test csv files are loaded so they can be loaded when running tests via `swift test`

I also added support for running the tests on Linux to make sure the library works on that platform. There is a simple `Dockerfile` to run the tests by running `docker build .` in the root of the project.

### CODE REVIEW

**Comment by swiftylondon** [comment]
@kgn  looks like Travis CI breaking again
Code 65 error appears to be a known issue: 

https://github.com/travis-ci/travis-ci/issues/6675

**Comment by swiftylondon** [comment]
Looks good - nice one.

**Comment by swiftylondon** [comment]
@naoty  I don't seem to have permission levels to merge.  Can you do it? Merge to develop and lets push this out!  Nice work @kgn  - thanks!

**Comment by swiftylondon** [comment]
unless @kgn  can you fix the conflicts by pulling latest develop?

**Comment by kgn** [comment]
I must be doing something wrong, I ran:

```
git remote add naoty https://github.com/naoty/SwiftCSV
git fetch naoty
git checkout -b naoty naoty/develop
```

But getting:

```
fatal: Cannot update paths and switch to branch 'naoty' at the same time.
Did you intend to checkout 'naoty/develop' which can not be resolved as commit?
```

**Comment by kgn** [comment]
@swiftylondon all my changes were after your last commit to `develop` so not sure what GitHub is complaining about

**Comment by grantkemp** [comment]
@kgn  it looks like there are some conflicts...^^ can you resolve them?

**Comment by DivineDominion** [comment]
@kgn I'm by no means a SwiftPM expert, so could you have a look at the state of everything now that the repository is cleaned up a bit?

**Comment by DivineDominion** [comment]
Closed via #77 as a working example

**Pull request closed without merging**
