### PR TITLE
Add Privacy Manifest

### LINKED ISSUE #137: Add Privacy Manifest to SPM and Carthage and CocoaPods build
Resources:

https://www.avanderlee.com/xcode/missing-api-declaration-required-reason-itms-91053/
https://mjtsai.com/blog/2024/04/05/embedding-a-privacy-manifest-into-an-xcframework/
https://www.privacymanifest.dev/
https://www.donnywals.com/how-to-add-a-privacy-manifest-file-to-your-app-for-required-reason-api-usage/

### PR DESCRIPTION
**Pull request by DivineDominion**
Fixes #137

### CODE REVIEW

**Comment by DivineDominion** [comment]
@Diggory @lardieri  Can you folks maybe double-check I didn't break or overlook anything? Will test in app in the meantime.

**Review by Diggory — APPROVED** [review]
Looks good to me.

**Review by lardieri — APPROVED** [review]
Agreed, looks good.

Apple is very quick to send the “we noticed one or more issues” email now. If you create a new app project, add the framework, upload the archive to TestFlight, and _don’t_ get an email after five minutes — then I think you can say the test passes. :-)

**Comment by DivineDominion** [comment]
Today, I've been stupid and tried with a macOS app -- where the Manifest isn't yet mandatory. So maybe I don't get an email at all. Will try with an iOS app later.

**Pull request merged**
